// Tile dimensions: 135 x 200 + padding for "hitbox"
export const DEFAULT_TILE_WIDTH = 135;
export const DEFAULT_TILE_HEIGHT = 200;
export const DEFAULT_TILE_HITBOX_MARGIN = 15; // become a % ?
export const DEFAULT_TILE_PIN_RADIUS = 5;
export const DEFAULT_TILE_HITBOX = DEFAULT_TILE_HITBOX_MARGIN + DEFAULT_TILE_PIN_RADIUS;
export const DEFAULT_TILE_FULL_WIDTH = DEFAULT_TILE_WIDTH + 2 * DEFAULT_TILE_HITBOX;
export const DEFAULT_TILE_FULL_HEIGHT = DEFAULT_TILE_HEIGHT + 2 * DEFAULT_TILE_HITBOX;
