image: node:latest
stages:
  - build
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
before_script:
  - npm install
build:
  stage: build
  script:
    - npm run rollup
  artifacts:
    paths:
      - dist
  tags:
    - docker-runner-02
publish_gitlab_registry:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  dependencies:
    - build
  tags:
    - docker-runner-02
  script:
    - npm config set @sources:registry https://${CI_SERVER_HOST}/api/v4/projects/229/packages/npm/
    - npm config set -- '//${CI_SERVER_HOST}/api/v4/projects/229/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config list
    - npm publish
  #rules:
    #- if: $CI_COMMIT_TAG
