enum ModalTypes {
  CUSTOMIZED_ACTIONS = 'CUSTOMIZED_ACTIONS',
  LABELLING = 'LABELLING',
  LINK = 'LINK',
  RULES = 'RULES',
  TAGS = 'TAGS',
  LISTS = 'LISTS',
  LISTS_ADD_TO_LIST = 'LISTS_ADD_TO_LIST',
  LISTS_CREATE_LIST = 'LISTS_CREATE_LIST',
  LISTS_REMOVE_LIST = 'LISTS_REMOVE_LIST',
  BROWSER_CREATE_FORM_TEMPLATE = 'BROWSER_CREATE_FORM_TEMPLATE',
  BROWSER_OVERWRITE_FORM_TEMPLATE = 'BROWSER_OVERWRITE_FORM_TEMPLATE',
  CASES_CREATE_CASE = 'CASES_CREATE_CASE',
  GRAPH_OBJECT_FUSION = 'GRAPH_OBJECT_FUSION',
  GRAPH_OBJECT_FISSION = 'GRAPH_OBJECT_FISSION', // un-fuse
}

export default ModalTypes;
